version: '2'
services:
  dav:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html/server
    ports:
      - "8080:80"
      
  davacl:
    build:
      context: .
      dockerfile: Dockerfile_acl
    volumes:
      - ./src:/var/www/html/server
    ports:
      - "8181:80"
